#This qsub script is designed for the Smithsonian Hydra cluster.

# - **This assumes you have sequentially numbered fasta files that you will be starting**
# - Change the line with "-t 1-100" to match the number of fasta files you have
# - Change "youremail@domain.com" to your email address in the "sap" line

#$ -q mThC.q
#$ -S /bin/sh
#$ -j y
#$ -cwd
#$ -l mres=2G,h_data=2G,h_vmem=2G
#$ -o job-$TASK_ID.out
#$ -N SAP
#$ -t 1-100

module load bioinformatics/sap/1.9.4

echo + `date` job $JOB_NAME started in $QUEUE with jobID=$JOB_ID on $HOSTNAME

# Create a directory for this run and move the fasta file
mkdir $SGE_TASK_ID
cd $SGE_TASK_ID || exit 1
mv ../$SGE_TASK_ID.fasta . || exit 1

# Start the sap job
sap -e youremail@domain.com -x 90 -x 80 --minidentity 0.7 $SGE_TASK_ID.fasta &>$SGE_TASK_ID.log

# Delete cache folders
rm -rf project*/*cache*

echo = `date` job $JOB_NAME done
